OnlineShop/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Data;
using OnlineShop.Models;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductController(ApplicationDbContext db, IWebHostEnvironment hostEnvironment)
        {
            _db = db;
            _hostEnvironment = hostEnvironment;
        }

        //Index Get Action Method
        public IActionResult Index()
        {
            var productList = _db.Products.Include(p => p.ProductTypes).Include(p => p.Tag).ToList();
            return View(productList);
        }


        // Create Get Action Method
        public IActionResult Create()
        {
            ViewBag.ProductTypes = _db.ProductTypes.ToList().Select(pt => new SelectListItem()
            {
                Text = pt.ProductType,
                Value = pt.Id.ToString()
            });

            ViewBag.Tags = _db.Tags.ToList().Select(t => new SelectListItem()
            {
                Text = t.Name,
                Value = t.Id.ToString()
            });
            return View();
        }


        // Create Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if(image != null)
                {
                    var pathName = Path.Combine(_hostEnvironment.WebRootPath + "/images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(pathName, FileMode.Create));
                    product.ImageUrl = "images/"+ image.FileName;
                }

                if(image == null)
                {
                    product.ImageUrl = "images/ImageNotAvailable.jpg";
                }

                await _db.Products.AddAsync(product);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.ProductTypes = _db.ProductTypes.ToList().Select(pt => new SelectListItem()
            {
                Text = pt.ProductType,
                Value = pt.Id.ToString()
            });

            ViewBag.Tags = _db.Tags.ToList().Select(t => new SelectListItem()
            {
                Text = t.Name,
                Value = t.Id.ToString()
            });
            return View(product);
        }

    }
}

OnlineShop/Areas/Admin/Controllers/ProductTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Data;
using OnlineShop.Models;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductTypeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ProductTypeController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var productTypeList = _db.ProductTypes.ToList();
            return View(productTypeList);
        }

        // Create Get Action Method

        public IActionResult Create()
        {
            return View();
        }

        // Create Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductTypes model)
        {
            if (ModelState.IsValid)
            {
                await _db.ProductTypes.AddAsync(model);
                await _db.SaveChangesAsync();

                TempData["save"] = "Product type has been saved successfully";
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // Edit Get Action Method

        public IActionResult Edit(int id)
        {
            if (id > 0)
            {
                var productType = _db.ProductTypes.Find(id);

                if (productType == null)
                {
                    return NotFound();
                }

                return View(productType);
            }

            return NotFound();

        }

        // Edit Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductTypes model)
        {
            if (ModelState.IsValid)
            {
                _db.ProductTypes.Update(model);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // Details Action Method
        public IActionResult Details(int id)
        {
            if (id > 0)
            {
                var productType = _db.ProductTypes.Find(id);

                if (productType == null)
                {
                    return NotFound();
                }

                return View(productType);
            }

            return NotFound();

        }

        // Delete Get Action Method

        public IActionResult Delete(int id)
        {
            if (id > 0)
            {
                var productType = _db.ProductTypes.Find(id);

                if (productType == null)
                {
                    return NotFound();
                }

                return View(productType);
            }

            return NotFound();

        }

        // Delete Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ProductTypes model)
        {
            if (ModelState.IsValid)
            {
                _db.ProductTypes.Remove(model);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }


    }
}

OnlineShop/Areas/Admin/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Data;
using OnlineShop.Models;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TagController : Controller
    {
        private readonly ApplicationDbContext _db;

        public TagController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var tagList = _db.Tags.ToList();
            return View(tagList);
        }

        // Create Get Action Method

        public IActionResult Create()
        {
            return View();
        }

        // Create Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Tag model)
        {
            if (ModelState.IsValid)
            {
                await _db.Tags.AddAsync(model);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // Edit Get Action Method

        public IActionResult Edit(int id)
        {
            if (id > 0)
            {
                var tag = _db.Tags.Find(id);

                if (tag == null)
                {
                    return NotFound();
                }

                return View(tag);
            }

            return NotFound();

        }

        // Edit Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Tag model)
        {
            if (ModelState.IsValid)
            {
                _db.Tags.Update(model);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // Details Action Method
        public IActionResult Details(int id)
        {
            if (id > 0)
            {
                var tag = _db.Tags.Find(id);

                if (tag == null)
                {
                    return NotFound();
                }

                return View(tag);
            }

            return NotFound();

        }

        // Delete Get Action Method

        public IActionResult Delete(int id)
        {
            if (id > 0)
            {
                var tag = _db.Tags.Find(id);

                if (tag == null)
                {
                    return NotFound();
                }

                return View(tag);
            }

            return NotFound();

        }

        // Delete Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Tag model)
        {
            if (ModelState.IsValid)
            {
                _db.Tags.Remove(model);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }
    }
}

OnlineShop/Views/Shared/_ButtonsPartial.cshtml
@model int


<div class="btn-group" >
    <a asp-action="Edit" asp-route-id="@Model" class="btn btn-warning"><i class="fas fa-edit text-white"></i></a>
    <a asp-action="Details"  asp-route-id="@Model"class="btn btn-info"><i class="fas fa-info-circle"></i></a>
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
</div>

OnlineShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/dadab0048a.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductType" asp-action="Index">Product Type</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Tag" asp-action="Index">Tag</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - OnlineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>